#define ABOUTDLGBOX        100
#define SETTINGSDLGBOX     101

#define TTYACCEL           200
#define TTYMENU            300
#define TTYICON            400
#define TTYBITMAP          500

#define IDD_OK             1
#define IDD_CANCEL         2

#define IDM_CONNECT        0x100
#define IDM_DISCONNECT     0x101
#define IDM_EXIT           0x102
#define IDM_SETTINGS       0x103
#define IDM_ABOUT          0x104

#define IDD_ABOUTICON      0x210
#define IDD_TITLELINE      0x211
#define IDD_VERSION        0x212
#define IDD_BYLINE         0x213
#define IDD_WINDOWSMODE    0x214
#define IDD_FREEMEM        0x215
#define IDD_RESOURCES      0x216

#define IDD_PORTCB         0x220
#define IDD_BAUDCB         0x221
#define IDD_DATABITSCB     0x222
#define IDD_PARITYCB       0x223
#define IDD_STOPBITSCB     0x224
#define IDD_DTRDSR         0x225
#define IDD_RTSCTS         0x226
#define IDD_XONXOFF        0x227
#define IDD_AUTOWRAP       0x228
#define IDD_NEWLINE        0x229
#define IDD_LOCALECHO      0x22A
#define IDD_FONT           0x22B
#define IDD_USECNRECEIVE   0x22C
#define IDD_DISPLAYERRORS  0x22D
#define IDC_CYCLE_PATH     0x22E

#define IDS_BYLINE         0x300
#define IDS_MODE_STANDARD  0x301
#define IDS_MODE_ENHANCED  0x302
#define IDS_MODE_WLO       0x303
#define IDS_MODE_UNDEF     0x304

#define IDS_COMPREFIX      0x310

#define IDS_BAUD111861     0x320
#define IDS_BAUD123137     0x321

#define IDS_PARITYNONE     0x330
#define IDS_PARITYEVEN     0x331
#define IDS_PARITYODD      0x332
#define IDS_PARITYMARK     0x333
#define IDS_PARITYSPACE    0x334

#define IDS_ONESTOPBIT     0x340
#define IDS_ONE5STOPBITS   0x341
#define IDS_TWOSTOPBITS    0x342
